### ISSUE TITLE
core: implement user tracking

### ISSUE THREAD

**Issue by AnnikaCodes** [AnnikaCodes/expecto-botronum#13]
- [x] a `Connection.userlist` attribute mapping `User`s to lists of roomids that's modified upon receiving a `Message` of type `join` or `leave`. (f8324ccc40db78cb8cb547c558eef572bc0e95dc)
- [x] a `Connection.getUser(id)` attribute that can fetch a `User` object from the room's `userlist` (f8324ccc40db78cb8cb547c558eef572bc0e95dc)
- [x] ways to prevent duplicating `User` objects - a check under `Connection.userlist` for other rooms the user is in, perhaps? (f8324ccc40db78cb8cb547c558eef572bc0e95dc)
- [x] `/userlist` on joining a room + handler (e331f2ed4b0cb26ee3cd09da3573e39d919a3dd1)
